image: node:16.14.0

definitions:
  steps:
    - step: &vulnerability-audit
        name: Vulnerability Audit
        caches:
          - node
        script:
          - apt-get update && apt-get install zip yarn -y
          - yarn install
          - yarn audit
    - step: &build-backend
        name: Build Backend
        caches:
          - node
        script:
          - apt-get update
          #- apt-get update && apt-get install libglib2.0-0 -y
          #- apt-get update && apt-get install libglib2.0-dev -y 
          #- apt-get update && apt-get install libnss3  -y
          #- apt-get update && apt-get install libatk1.0-0 -y  
          #- apt-get update && apt-get install libatk1.0-dev -y
          #- apt-get update && apt-get install libatk-bridge2.0-0 -y 
          #- apt-get update && apt-get install libxcomposite1 -y
          #- apt-get update && apt-get install libxdamage1 -y
          #- apt-get update && apt-get install libxfixes3 -y
          #- apt-get update && apt-get install libxrandr2 -y
          #- apt-get update && apt-get install libgbm1 -y
          #- apt-get update && apt-get install libxkbcommon0 -y 
          #- apt-get update && apt-get install libasound2 -y
          - apt-get update && apt-get install zip yarn -y
          #- apt-get update && apt-get install zip yarn -y
          - yarn install
          - yarn build
          #- npx puppeteer browsers install chrome
          # Exclude files to be ignored
          - zip -r app-$BITBUCKET_BUILD_NUMBER.zip . -x *.git* bitbucket-pipelines.yml
        artifacts:
          - "*.zip"

pipelines:
  # pull-requests:
  #   '**':
  #     - step: *vulnerability-audit
  branches:
    develop:
      - step: *build-backend
      - step:
          name: Deploy to Azure SIT
          deployment: SIT
          script:
            - pipe: atlassian/azure-web-apps-deploy:1.0.1
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
                AZURE_APP_NAME: $AZURE_APP_NAME
                ZIP_FILE: app-$BITBUCKET_BUILD_NUMBER.zip
    uat:
      - step: *build-backend
      - step:
          name: Deploy to Azure UAT
          deployment: UAT
          script:
            - pipe: atlassian/azure-web-apps-deploy:1.0.1
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
                AZURE_APP_NAME: $AZURE_APP_NAME
                ZIP_FILE: app-$BITBUCKET_BUILD_NUMBER.zip
    master:
      - step: *build-backend
      - step:
          name: Deploy to Azure PROD-A
          deployment: PROD-A
          script:
            - pipe: atlassian/azure-web-apps-deploy:1.0.1
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
                AZURE_APP_NAME: $AZURE_APP_NAME
                ZIP_FILE: app-$BITBUCKET_BUILD_NUMBER.zip
      - step:
          name: Deploy to Azure PROD-B
          deployment: PROD-B
          script:
            - pipe: atlassian/azure-web-apps-deploy:1.0.1
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: $AZURE_RESOURCE_GROUP
                AZURE_APP_NAME: $AZURE_APP_NAME
                ZIP_FILE: app-$BITBUCKET_BUILD_NUMBER.zip